### ISSUE TITLE
associate antilope to a private bittorrent tracker

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/antilope#129]
- [ ] allow to upload .torrent files
- [ ] add a tracker parameters
- [ ] check for torrents metadatas and add those
- [ ] add a proxy to recirect announces
