### ISSUE TITLE
PHPStan ? PHPCS ? GH Actions ?

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/antilope#17]
So, would you be interested for a setup of _ye olde_ php toolchain:
- [x] PHPStan for static analysis (+ symfony plugin) (#19)
- [x] PHPCS for style checkink (PSR12) (#23)
- [x] GitHub Action to run these checks on pull requests and master (#35)

In addition I could add a command in Symfony console that run the checks to easily check before committing.

**Comment by vincent-peugnet** [comment]
# OH YEAH BB :1st_place_medal: 

*les embrouilles commencent...*
